### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Applr-techport** [voxeet/voxeet-uxkit-cordova#10]
Is there a way to modify ui in cordova javascript source?

When default video is false, the proximity sensor does not turn off the screen even if you do not make a voxeet call.

Is there a way to solve this?

**Comment by codlab** [comment]
No possibility to modify the ui from the cordova side currently.

What platform?

Avoid mixing multiple requests in a single ticket.

**Comment by codlab** [comment]
Without activity I'm closing this issue. We'll definitively work in the future to add some features for hybrid customisation.

Concerning the screen sensor, make sure that you made the proper configuration to add the wake permission in the AndroidManifest
