### ISSUE TITLE
liveRecording param seems to be ignored

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-uxkit-cordova#16]
**Describe the bug**

No recording is generated and no webhook is received. 

**Expected Behaviour**

Record the conference, same as through the react web version

**Minimalistic code (recommended)**

```
const { Voxeet, UserType } = VoxeetSDK;

Voxeet.initializeToken("YOUR_CONSUMER_KEY", "YOUR_CONSUMER_SECRET")
.then(() => Voxeet.defaultBuiltInSpeaker(true))
.then(() => Voxeet.defaultVideo(true))
.then(() => Voxeet.connect(new UserInfo(id, name, avatar)))
.then(() => Voxeet.create({alias: conferenceAlias, params: {liveRecording: true}}))
.then(result => Voxeet.join(result.conferenceId))
.catch(err => alert(err));
```

**Specifications**

  - Device: iPhone 7
  - OS: iOS 12.3.1
  - Platform: iOS

**Comment by VTCoco** [comment]
Hello @youssmak, `liveRecording` parameter isn't enough to start a recording.
The `liveRecording` parameter is only here to activate the record **during** the conference (mp3, MP4), but it will not start the record automatically.

We need to expose the `record` method for Cordova: https://github.com/voxeet/voxeet-ios-sdk#record-conferences so it's more like an improvement than a bug.

**Comment by codlab** [comment]
Bundled within the 1.2.2, this feature is available through

```
create({
conferenceAlias: "something",
  params: {
    liveRecording: true
  }
})
```

to actually trigger the recording (or stop it :

```
startRecording(): Promise<void>
stopRecording(): Promise<void>
```

**Comment by youssmak** [comment]
Thks @codlab 
Doest i have to start recording afeter calling the broadcast method?
Is the recording automatically stopped when the end call red button is touched ?

----

const { Voxeet, UserType } = VoxeetSDK;

Voxeet.initializeToken("YOUR_CONSUMER_KEY", "YOUR_CONSUMER_SECRET")
.then(() => Voxeet.defaultBuiltInSpeaker(true))
.then(() => Voxeet.defaultVideo(true))
.then(() => Voxeet.connect(new UserInfo(id, name, avatar)))
.then(() => Voxeet.create({alias: conferenceAlias, params: {liveRecording: true}}))
.then(result => Voxeet.broadcast(result.conferenceId))
.then(result => Voxeet. startRecording(result.conferenceId))
.catch(err => alert(err));
