### ISSUE TITLE
XCode 11.2 build issue

### ISSUE THREAD

**Issue by weiz18** [voxeet/voxeet-uxkit-cordova#21]
Hey,

We are getting the following issue when we upgraded our build stack to to XCode 11.2 

`Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9)`

Thanks

**Comment by VTCoco** [comment]
This should be patch with the new release 1.3.12 @weiz18
