### ISSUE TITLE
Plugin Install fails due to "Incompatible Swift Version"

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#27]
**Describe the bug**

Install of cordova-plugin-voxeet fails with  the following error: `Incompatible Swift version - framework was built with 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15) and the local version is 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29).`

Full error: https://gist.github.com/mattyg/6b0f3d5bcfb1ee4870211ea3b1074aab

**Expected Behaviour**

Plugin installs successfully.

**Steps to Reproduce the Problem**

On OSX 10.15.4, xcode 11.4, and carthage 0.34.0

  1. `cordova platform remove ios`
  2. `cordova platform add ios`
  3. `cordova plugin install cordova-plugin-voxeet`

**Minimalistic code (recommended)**

Full error message: https://gist.github.com/mattyg/6b0f3d5bcfb1ee4870211ea3b1074aab

**Specifications**

  - OSX 10.15.4
  - xcode 11.4
  - carthage 0.34.0

**Comment by VTCoco** [comment]
An update will be provided today to resolve this point, thank you for your report.

**Comment by VTCoco** [comment]
Swift 5.2 support with v1.3.24. :)
