### ISSUE TITLE
Incoming Call Notifications Displayed after Disconnect from Voxeet

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#29]
**Describe the bug**

After calling Voxeet.disconnect(), the device still receives incoming call notices. When I click "accept" on these incoming call notices, the call is not joined.

**Expected Behaviour**

After calling Voxeet.disconnect(), the device should not longer receive incoming call notices, until Voxeet.initializeToken() and Voxeet.connect() are called again.

**Steps to Reproduce the Problem**

1. On device A, initialize Voxxet, connect as UserInfo 1
2. On device B, initialize Voxxet, connect as UserInfo 2
3. On device B, disconnect from Voxeet
3. On device A, start a conference, invite UserInfo 2
*Incoming call notice appears on device B*

**Specifications**

  - Platform: Android

**Comment by codlab** [comment]
The disconnect() is not meant to prevent invitation to be received but to make the participant stop local activity. If a disconnected user receives invitation they normally will trigger the proper flow when the sdk is initialized.

this is why in such cases, it’s mandatory to use the VoxeetSDK.initialize() in the native part of it’s not made available when the Cordova engine starts.

In the later case, when the non native engine calls the initialization, it will as well manage the action which triggered if you made the proper metadata parameter in the AndroidManifest to make aware the SDK to statically starts your com.yourcompany.acme.MainActivity

**Comment by mattyg** [comment]
Is there another function to stop the participant from receiving incoming call notifications? 

Should I call connect() again as a placeholder "Blank" user that will never be sent an invitation before then calling disconnect()?

My issue is not that clicking "Accept" fails to start the call. My issue is that I want to stop the device from receiving incoming call notifications after my user has been logged out, and resume receiving incoming call notifications after they log back in.

Thanks for your help!

**Comment by mattyg** [comment]
@codlab Checking in on this again. 

Please let me know how I can disconnect a participant from Voxeet such that they do not receive incoming call notifications intended for the previously-connected participant.

**Comment by mattyg** [comment]
My mistake - I am unable to reproduce the issue in a minimal example.

Sorry about that and thanks for your help.
