### ISSUE TITLE
Self-facing video does not appear when re-joining conference on android

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#35]
**Describe the bug**

Upon re-joining an existing conference, the self-facing video overlay does not appear, only the other participant's video appears.  I have only produced this issue on android and have not yet tested it on ios.

**Expected Behaviour**

The self-facing video appears when joining a conference initially, or re-joining it subsequently.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch `no-hud-video-bug`) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Follow the steps below to reproduce:

1.
  - Device A, tap "Connect" button
  - Device B, tap "Connect" button

2.
  - Device A, tap "Create Conference"
  - Device B, enter the conference id from device A and tap "Join Conference"

3. 
  - Device A, hang up conference
  - Device A, tap "Join Conference"
  (or)
  - Device B, hang up conference
  - Device B tap "Join Conference"

**Upon re-joining the conference, the self-facing video overlay does not appear, only the other device's video is shown**

**Specifications**

  - Device: 
  - OS: Android 8, 9
  - Platform: Android 
  - Subsystem: [e.g. n.a., CyanogenMod, ...]
  - Version:
    - latest version of voxeet-uxkit-cordova 1.3.33

**Comment by FabienLavocat** [comment]
Thank you @mattyg for reporting this issue, we are working on it and will get back to you as soon as we have a solution.

**Comment by mattyg** [comment]
It looks like this was resolved in the 1.4.0 release last week. Thanks.

In the future, could you please update these tickets when they have been addressed or resolved? I had no idea the recent release addressed this issue.
