### ISSUE TITLE
No Video from either participant when joining from "Incoming Call" notice on iOS

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#36]
**Describe the bug**

When joining a conference from an incoming call notice on iOS, neither participants video is shown, only a grey background.

Very inconsistently, the video for both participants does appear properly.

**Expected Behaviour**

Both participants video is shown when joining a conference from an incoming call notice on iOS.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Follow the steps below to reproduce:

Device A, tap "Connect" button
Device B (iOS), tap "Connect" button

Device A, tap "Create Conference"
Device A, enter the "Connected as" user name displayed on Device B and tap "Invite User"

Device B (iOS) Accept the "Incoming Call" notice

**Upon joining the conference, neither the self-facing nor other participants video is shown. Instead only a grey background is shown.**

**Specifications**
  - Device A: Android 8, Moto G4
  - Device B: iPhone X, running iOS 14.0.1
  - Latest plugin and sdk release 1.3.35

**Comment by FabienLavocat** [comment]
Thank you @mattyg for reporting this issue, we are working on it and will get back to you as soon as we have a solution.

**Comment by VTCoco** [comment]
Do you hear at least the other participant or neither audio & video are available @mattyg?

**Comment by mattyg** [comment]
@VTCoco  Device B does not get audio nor video.

**Comment by VTCoco** [comment]
Ok thank you for your report, we are working on it. https://github.com/voxeet/voxeet-uxkit-cordova/issues/37 is also related to  this one. 👍

**Comment by mattyg** [comment]
Just checking in on this @VTCoco. Do you have any eta for when the issue will be resolved? Thanks!

**Comment by VTCoco** [comment]
Everything is fixed on our side, we are now testing before the v3.0.1 release 👍

**Comment by VTCoco** [comment]
Hello with the https://github.com/voxeet/voxeet-uxkit-cordova/releases/tag/v1.4.2 release that is using our v3.0.1 VoxeetSDK, this ticket is resolved.
