### ISSUE TITLE
Incoming call notices inconsistently not appearing on iOS

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#37]
**Describe the bug**

Inconsistently, incoming call notices on iOS do not appear, but the device rings / vibrates as expected.

**Expected Behaviour**

Incoming calls should always display an incoming call notice when the app is open and connected to Voxeet.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Both devices used were on iOS.

Follow the steps below to reproduce:

- Device A: connect to voxeet
- Device B: connect to voxeet

- Device A: Create conference
- Device A: invite user on device B
- Device B: click "Accept" on incoming call notice
- Device B: Hang up call

- Device A: invite user on device B
- Device B: click "Accept" on incoming call notice
- Device B: Hang up call

- Device A: invite user on device B

**Device B vibrates / rings as if incoming call notice is coming in, but no such incoming call notice is displayed**

**Specifications**
  - OS: iOS

**Comment by VTCoco** [comment]
Hello with the https://github.com/voxeet/voxeet-uxkit-cordova/releases/tag/v1.4.2 release that is using our v3.0.1 VoxeetSDK, this ticket is resolved.
