### ISSUE TITLE
Speaker button disabled when conference joined with headphones

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#38]
**Describe the bug**

When joining a conference with headphones plugged in, the speaker button is disabled. Upon removing the headphones, the speaker button remains disabled.

**Expected Behaviour**

If headphones are removed, the speaker button should become enabled and toggled "on".

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Both devices used were on Android.

Follow the steps below to reproduce:

- Device A: connect to voxeet
- Device B: Plug in headphones
- Device B: connect to voxeet

- Device A: Create conference
- Device A: invite user on device B

- Device B: click "Accept" on incoming call notice

**Speaker button is disabled on device B. Tapping it does nothing.**

- Device B: remove headphones

**Speaker button is still disabled on device B. Tapping it still does nothing. There is no audio from the other participant coming out of the device speakers.**

**Specifications**

  - Device: Android
  - OS: 8 & 9
  - Version:
    - latest cordova-plugin-voxeet

**Comment by FabienLavocat** [comment]
@mattyg when you click the Speaker button, do you get a modal window asking you to pick an audio output?
Since the UXKit for Cordova is using the Android UXKit, I ran some tests using the native UXKit for Android and I can't reproduce the problem.

**Comment by mattyg** [comment]
> @mattyg when you click the Speaker button, do you get a modal window asking you to pick an audio output?
> Since the UXKit for Cordova is using the Android UXKit, I ran some tests using the native UXKit for Android and I can't reproduce the problem.

@FabienLavocat  No, I do not get a modal window. Can you reproduce the issue using this plugin in the minimal example repo linked above?

**Comment by FabienLavocat** [comment]
@mattyg when I plug/unplug the headphones, the status of the Speaker button changes for me. I need to keep investigating more.

**Comment by FabienLavocat** [comment]
@mattyg in your code sample, could you upgrade to the version 1.4.0 of the plugin:
`"cordova-plugin-voxeet": "^1.4.0",`
https://github.com/mattyg/voxeet-cordova-example/blob/no-hud-video-bug/src-cordova/package.json#L20

**Comment by c4techweb** [comment]
@FabienLavocat I updated the plugin to 1.4.0.

Now when I unplug the headphones, the Speaker button is enabled again and tapping it opens the modal window. However the modal window is empty -- there are no sound output options to choose. I still don't hear audio out of the speaker.

**Comment by mattyg** [comment]
@FabienLavocat I updated the code sample to use 1.4.0.

Now when I unplug the headphones, the Speaker button is enabled again and tapping it opens the modal window. However the modal window is empty -- there are no sound output options to choose. I still don't hear audio out of the speaker.

**Comment by mattyg** [comment]
@FabienLavocat With the 1.4.2 release, the behavior changed slightly:

When I unplug the headphones, the Speaker button is enabled again and toggled "off." Tapping it opens the modal window with the text "Media output" and no other content. **I hear audio out of the "ear piece" speaker, not the "speaker-phone" speaker**

**Comment by mattyg** [comment]
@FabienLavocat Just checking on this -- do you have an ETA when this will be resolved?

**Comment by mattyg** [comment]
Just checking on this again -- do you have an ETA when this will be resolved?

**Comment by mattyg** [comment]
This core issue was resolved in the 1.4.5. Thank you!

The speaker button is no longer disabled when joining a conference with headphones. When the headphones are removed, the speaker button remains enabled, and audio output switches to the device speaker.

However, conference audio plays out of the "ear-piece" speaker not the "speaker-phone" speaker. Tapping the speaker button opens a modal window with the text "Media output" and no other content. I created a seperate ticket for this issue (#41)

Also, I realized that the UX of the speaker button is confusing and misleading. When audio is playing out of the headphones, the speaker button is toggled "on", and when it is playing out of the speaker, it is toggled "off". I will create a seperate ticket for this issue (#42)

In the future would you mind updating relevant tickets when issues are resolved by new versions? Thanks.
