### ISSUE TITLE
Speaker audio off, despite calling Voxeet.defaultBuiltInSpeaker(true) before joining conference

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#39]
**Describe the bug**

Calling `Voxeet.defaultBuiltInSpeaker(true)` before joining a conference does not cause the speaker to be enabled by default.

Very inconsistently, the device speaker is enabled when joining the conference, as expected.

**Expected Behaviour**

Every time a user joins a conference after calling `Voxeet.defaultBuiltInSpeaker(true)`, the other participants audio will be played out of the built-in device speaker, without needing to toggle the speaker button.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Both devices used were on Android.

Follow the steps below to reproduce:

- Device A: connect to voxeet
- Device B: connect to voxeet

- Device A: Create conference
- Device A: invite user on device B

- Device B: click "Accept" on incoming call notice

**Inconsistently, the speaker button is toggled "off" and no audio comes out of the device built-in speakers. Upon clicking the speaker button, audio comes out of the device built-in speakers**

**Specifications**

  - Device: Android
  - OS: Android 8 & 9
  - Version: latest cordova-plugin-voxeet

**Comment by feded** [comment]
I have the same problem with Android, iOS working as expected. Any solution on this?

**Comment by FabienLavocat** [comment]
Sorry for the delay, we are still looking into it. Our 3.0.1 release on Monday will fix most of the issues reported.

**Comment by mattyg** [comment]
@FabienLavocat I'm still experiencing the issue on Android with the 1.4.2 release, though it has changed slightly:

Conference audio plays out of the "ear-piece" speaker not the "speaker-phone" speaker, and the button is toggled "off." Tapping the button opens a modal window with the text "Media output" and no other content. The behavior is now consistent.

**Comment by mattyg** [comment]
@FabienLavocat Just checking on this -- do you have an ETA when this will be resolved?

**Comment by mattyg** [comment]
Just checking on this again -- do you have an ETA when this will be resolved?

**Comment by mattyg** [comment]
This core issue was resolved in the 1.4.5. Thank you! 

Speaker audio is now enabled by default after calling `Voxeet.defaultBuiltInSpeaker(true)` before joining conference.

However, conference audio plays out of the "ear-piece" speaker not the "speaker-phone" speaker. Tapping the speaker button opens a modal window with the text "Media output" and no other content. I will create a seperate ticket for this issue (#41)

In the future would you mind updating relevant tickets when issues are resolved by new versions? Thanks.
