### ISSUE TITLE
[Feature]  Fire cordova window event whenever an action is performed 

### ISSUE THREAD

**Issue by weiz18** [voxeet/voxeet-uxkit-cordova#40]
**Describe the bug**

Currently, there is no way to know when the callkit is opened, closed , minimised or maximise apart from the visual feedback, so we can't perform any additional actions in respond to those, for instance,  When a callkit is minimised,  we would like to be notified and provide additional information to user such as a dialog. 

**Expected Behaviour**

Getting notified when an action is performed in Uxkit.  For instance, this keyboard plugin fire a window event whenever keyboard is shown or hidden (https://github.com/cjpearson/cordova-plugin-keyboard/blob/7897856fc9df9ae3d017c824e2ba59079aff44bd/www/keyboard.js#L55). Something similar to this would be really helpful, because currently,

**Comment by FabienLavocat** [comment]
Hi @weiz18 this Pull Request #44 will add the conference events into the Cordova layer for Android. You will be able to know when the status of a conference changes.

**Comment by FabienLavocat** [comment]
We are now propagating the conference events in the Cordova layer with the latest version of the plugin.
