### ISSUE TITLE
Audio plays out of ear-piece speaker by default & unable to switch output speaker on Android

### ISSUE THREAD

**Issue by mattyg** [voxeet/voxeet-uxkit-cordova#41]
**Describe the bug**

On android devices with multiple speakers, conference audio plays out of the "ear-piece" speaker not the "speaker-phone" speaker. Tapping the speaker button opens a modal window with the text "Media output" and no other content.

**Expected Behaviour**

Conference audio plays out of the "speaker-phone" speaker by default. The "Media output" modal window contains a list of possible output devices. Tapping an output device makes audio output from that device.

**Steps to Reproduce the Problem**

See the minimalistic code example below.

**Minimalistic code (recommended)**

This repo (branch no-hud-video-bug) demonstrates the issue: https://github.com/mattyg/voxeet-cordova-example

Both devices used were on Android.

Follow the steps below to reproduce:

Device A: connect to voxeet

Device B: connect to voxeet

Device A: Create conference

Device A: invite user on device B

Device B: click "Accept" on incoming call notice

**Audio plays out of the ear-piece speaker**

Device B: tap the "speaker" button 

**A modal window opens with the text "Media Output" and nothing else**

**Specifications**

  - Device: Android 8 & 9

**Comment by codlab** [comment]
The v1.4.6-BETA1 should fix the issue.

Concerning the point `Conference audio plays out of the "speaker-phone" speaker by default`, a work on the default output will make it available _if set to default_ in an another release

**Comment by mattyg** [comment]
> The v1.4.6-BETA1 should fix the issue.

Thanks @codlab -- do you have an ETA for when v1.4.6 be out of beta and officially released?

**Comment by mattyg** [comment]
Hi @codlab just checking in again  -- do you have an ETA for when v1.4.6 be out of beta and officially released?

**Comment by mattyg** [comment]
@codlab I tested out a build using the branch `beta/v1.4.6` but the "Media Outputs" modal is still empty. Is that the issue that it is supposed to fix?

**Comment by codlab** [comment]
Can you give me the logs from your app?

The log should be at least from before the conference view is being shown and "after" a click on the list of devices.

The ear piece by default is still normal for now

**Comment by feded** [comment]
@codlab Even after calling "defaultBuiltInSpeaker(true)" before or after joining the conference, on Android devices I still have the ear-piece and has to be changed with the button. 

Ios works as expected. 

I'm going for a workaround to enable the speaker for now.

**Comment by codlab** [comment]
The package 1.4.7-BETA2 should introduce the fix for the speaker mode not being used properly

The previous list of devices in the 1.4.6-BETA1 is also bundled inside. If the list remains emty, I would need our app logs to check why the interface couldn't load the various items.

**Comment by codlab** [comment]
A new update is available containing this fix, the1.5.0 release has been pushed to make it working properly. Note that it introduces a change (unrelated to the issue in this ticket) where you will need to adapt the variable injected inside your project

You will need to replace the VoxeetSDK (window.VoxeetSDK) to VoxeetCordova. This VoxeetCordova contains a VoxeetSDK class instance and UserInfo class definition

from there you can use all the method like join, leave etc... via VoxeetSDK.join(...), VoxeetSDK.leave(...) ...
