### ISSUE TITLE
Video does not always appear after 1.4.6 update SDK 3.0.3

### ISSUE THREAD

**Issue by feded** [voxeet/voxeet-uxkit-cordova#43]
Video calls are inconsistent. The video is not always shown on a peer to peer call with defaultVideo set to true.

**Expected Behaviour**

Video should be shown on both peers after creating and joining a call. 

**Minimalistic code (recommended)**

```
//Caller: 
Voxeet.defaultBuiltInSpeaker(true)
                    .then(() => Voxeet.defaultVideo(true))
                    .then(() => Voxeet.create({conferenceAlias: this.conferenceId, alias: this.conferenceId}))
                    .then((conference) => { //notify opponent
 })

//Opponent: 
Voxeet.defaultBuiltInSpeaker(true)
                .then(() => Voxeet.defaultVideo(true))
                .then(() => Voxeet.join(voxeetConferenceId)
                    .then((call) => { 
                    // do stuff
})
```

**Specifications**

  - Platform: Android, iOS
  - SDK: 3.0.3
  - Cordova version: 1.4.6

**Comment by codlab** [comment]
The 1.4.7-BETA2 should address this part (as well as other sdk related fixes)

**Comment by feded** [comment]
Hi @codlab, this is also happening on the 1.4.7-BETA2 version. No exceptions are thrown.

**Comment by FabienLavocat** [comment]
Closing this issue, if this is still happening with the latest version of the SDK, please open a new ticket.
