### ISSUE TITLE
Customizing the UI - Displaying Custom Buttons on top of video.

### ISSUE THREAD

**Issue by bijanmmarkes** [voxeet/voxeet-uxkit-cordova#5]
**Describe the bug**
Hello, I have been working with this SDK for the past week now, I love what it is capable of, I finally got it working on my Ionic 4 project, and absolutely love the way it works. I know you may be getting sick of me posting issues but I don't know any other place to ask questions about this repo. My issue is that there is no documentation for this plugin, and I have no way of knowing how to customize the ui. How can I create my own custom ui? I need to add my own custom buttons and html on top of the video. Is this possible with this plugin? This is kind of a make it or break it condition for our company. I love this company and platform so far and would be a long-term customer if I can find a way to customize the UI and float my own HTML or UI on top of it.

**Expected Behaviour**
The ability to overlay custom HTML over the video and remove UI that is currently appended. Also the ability to have a non-conference format, I really need to customize everything about it and am really looking for simply making use of the HLS streaming. I really need to customize everything about my project, and it doesn't seem I have much control over this plugin although it seems possible using the javascript UI on the voxeet developer site. 

Is the only option to manually modify the plugin code and use my own repo? This wouldn't be too ideal for me as I don't want to have to maintain my own repo.

Thanks many in advance, and keep up the good work!

Regards.

**Comment by VTCoco** [comment]
Thank you for your feedback @bijanmmarkes, glad you like it :).

For now the only way to fully customize the UI is to fork both Android and iOS open sources repos, customize them natively and retrieve them with Cordova: 

Android: https://github.com/voxeet/android-sdk-toolkit
(and update with your forked repo: YOUR_PROJECT/node_modules/cordova-plugin-voxeet/src/android/build-extras.gradle)

iOS: https://github.com/voxeet/voxeet-ios-conferencekit
(and update with your forked repo: YOUR_PROJECT/node_modules/cordova-plugin-voxeet/src/ios/Cartfile)
