### ISSUE TITLE
Not compatible with cordova-android@10.1.1

### ISSUE THREAD

**Issue by youssmak** [voxeet/voxeet-uxkit-cordova#61]
**Describe the bug**

> FAILURE: Build completed with 2 failures.
> 
> 1: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':app:checkReleaseDuplicateClasses'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
>    > Duplicate class org.webrtc.AndroidVideoDecoder found in modules jetified-media-3.2.1-runtime (com.voxeet.sdk:media:3.2.1) and jetified-react-native-webrtc-1.92.2-jitsi-8711917-runtime (com.facebook.react:react-native-webrtc:1.92.2-jitsi-8711917)
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> Execution failed for task ':app:mergeReleaseNativeLibs'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
>    > 2 files found with path 'lib/x86/libc++_shared.so' from inputs:
>       - /Users/youssef/.gradle/caches/transforms-3/78996b9cc9ad3c386b5da03aa3699b7e/transformed/jetified-react-native-0.61.5-jitsi.2/jni
>       - /Users/youssef/.gradle/caches/transforms-3/32ab7df9ae0a3e50165da38d39839e2b/transformed/jetified-media-3.2.1/jni
>      If you are using jniLibs and CMake IMPORTED targets, see
>      https://developer.android.com/r/tools/jniLibs-vs-imported-targets
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

**Minimalistic code (recommended)**

```
cordova platform add android@10.1.1
cordova build android -- --gradleArg=-PcdvMinSdkVersion=23 --verbose
```

**Comment by codlab** [comment]
react-native-webrtc is incompatible with our library as both are using native webrtc integration and not aligned (integration of dolby technologies, bug fixes etc...). 
Therefore you can't use the voxeet cordova plugin and that library.

I also see that using cordova-android@10.1.1, nothing related to react-native is integrated at all which makes sense since vanilla Cordova wouldn't be integrating react-native tech. Did you integrate it manually?

**Comment by youssmak** [comment]
thks !
