### ISSUE TITLE
Cant install cordova plugin missing "Carthage/Build/VoxeetUXKit.xcframework"

### ISSUE THREAD

**Issue by Alexini** [voxeet/voxeet-uxkit-cordova#66]
Hello !
I use this plugin for a cordova app and I didn`t ahve any problem on Android platform, is working as expected but Ican't install it on IOS. After cordova-install I get:

Error: Command failed: /Users/interalia/Documents/Alexini Project/WorkoutMinister/WorkoutMinister/plugins/cordova-plugin-voxeet/carthage.sh update --use-xcframeworks --platform ios --no-use-binaries --project-directory /Users/interalia/Documents/Alexini Project/WorkoutMinister/WorkoutMinister/plugins/cordova-plugin-voxeet/src/ios
/bin/sh: /Users/interalia/Documents/Alexini: No such file or directory

And then
Cannot find framework "/Users/interalia/Documents/Alexini Project/WorkoutMinister/WorkoutMinister/plugins/cordova-plugin-voxeet/src/ios/Carthage/Build/VoxeetUXKit.xcframework" for plugin cordova-plugin-voxeet in iOS platform

Im using cordova 11.0.0 and xcode Version 12.5.1 (12E507)

Thanks for the help

**Comment by Alexini** [comment]
I solved it installing xcode 13 and then going to the cordova project root folder and 

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

after that i could install it.

**Comment by FabienLavocat** [comment]
You are right, the latest version of the UXKit for Cordova is using the iOS SDK version 3.3.3 and is compatible with XCode 13.2.
