### ISSUE TITLE
Can't upload the iOS bundle to AppStore

### ISSUE THREAD

**Issue by Alexini** [voxeet/voxeet-uxkit-cordova#67]
I was able to add the plugin upgrading xcode version to 13. 
I test my app and everything is working but then i try to archive the .ipa and upload it to the appStore but I face with this error

CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.onevcat.Kingfisher' under the iOS application 'WorkoutMinister.app'. With error code STATE_ERROR.VALIDATION_ERROR.90685 for id c3d0e0ae-8bce-4e4f-a335-2244043d4a3d

I look for information but it and I know that is caused by embed framework reference inside the xcframwork build but i dont know how to change this.

**Comment by FabienLavocat** [comment]
This is unlikely related to the SDK / UXKit, please checkout this Stackoverflow page: https://stackoverflow.com/questions/40005130/error-itms-90685-cfbundleidentifier-collision-there-is-more-than-one-bundle
