### ISSUE TITLE
voxeet-application script is missing from tar

### ISSUE THREAD

**Issue by Tallyb** [voxeet/voxeet-uxkit-cordova#7]
warning when installing the plugin:
Script file does't exist and will be skipped: /Users/vagrant/git/plugins/cordova-plugin-voxeet/voxeet_application.js
1.1.0 

While the file is on the github repo, it is not included in the npm tar file. You can download it from here to inspect: 
https://registry.npmjs.org/cordova-plugin-voxeet/-/cordova-plugin-voxeet-1.1.0.tgz

expected: add the file to tar file if required or remove it from the hook if not needed

**Comment by codlab** [comment]
This issue is resolving in the latests versions of the plugin
