### ISSUE TITLE
navigator.attachMediaStream() is not available in ionic

### ISSUE THREAD

**Issue by asadumair** [voxeet/voxeet-uxkit-cordova#71]
navigator.attachMediaStream() is not available ionic

this will use for the append different videos under desired div.

if (!videoNode) {
    videoNode = document.createElement("video");

    videoNode.setAttribute("id", "video-" + participant.id);
    videoNode.setAttribute("height", 240);
    videoNode.setAttribute("width", 320);
    videoNode.setAttribute("playsinline", true);
    videoNode.muted = true;
    videoNode.setAttribute("autoplay", "autoplay");

    const videoContainer = document.getElementById("video-container");
    videoContainer.appendChild(videoNode);
  }

  navigator.attachMediaStream(videoNode, stream);
  
  error: attachMediaStream is not found

**Comment by codlab** [comment]
The navigator's attachMediaStream is only available in regular browsers, Cordova and ionic are shipping a minimalist implementation (that's why currently only the UXKit's are supported by Cordova). Implementing custom video in the div is then not supported and only possible via native views
