### ISSUE TITLE
use of undeclared identifier 'VoxeetConferenceKit' / VoxeetSDK

### ISSUE THREAD

**Issue by Tallyb** [voxeet/voxeet-uxkit-cordova#8]
Cannot build iOS
mobile/platforms/ios/Operations/Plugins/cordova-plugin-voxeet/CDVVoxeet.m:22:10: error:
      use of undeclared identifier 'VoxeetSDK'
        [VoxeetSDK.shared initializeWithConsumerKey:consumerKey consumerSecret:consumerSecret u...
         ^
mobile/platforms/ios/Operations/Plugins/cordova-plugin-voxeet/CDVVoxeet.m:23:10: error:
      use of undeclared identifier 'VoxeetConferenceKit'
        [VoxeetConferenceKit.shared initialize];
         ^

1. add ios platform + plugin
2. cordova prepare
3. cordova build --buildFlag="-UseModernBuildSystem=0"

**Specifications**
cordova-plugin-voxeet 1.1.1 "Voxeet"
cordova 8.1.2
cordova-ios 4.5.5

**Comment by VTCoco** [comment]
What is your Xcode version?
I have a sample which works with the latest update. I have the same Cordova version and plugin:

"cordova-plugin-voxeet": {
            "version": "1.1.1",
            "resolved": "https://registry.npmjs.org/cordova-plugin-voxeet/-/cordova-plugin-voxeet-1.1.1.tgz",
            "integrity": "sha512-9Fu0QOXcxunX1A8NfznSYDRKzY4ksGuQvInKS7GMt36K3vXRJHAm3kgC4tO7XwkoaT0Kt1EVdmkWFVfOpIOQcw=="
        }

**Comment by Tallyb** [comment]
XCode 10.2 (local and on CI)
It works on the CI but does not work locally. Any thought?

**Comment by VTCoco** [comment]
"does not work locally" means it isn't working with Xcode? 
Does your Xcode command line tools is also running on the last Xcode release? (do you have multiple Xcode version on your Mac which may cause your bug?)

It's a little weird ^^

**Comment by VTCoco** [comment]
I have found some interesting blogs, the ABI of Swift should be now stable with the 5.0 version:

https://medium.com/swiftify/swift-5-and-abi-stability-the-best-time-to-migrate-d4029d5342e9

https://swift.org/blog/abi-stability-and-more/

So I hope I will not upload a new version of Voxeet SDKs frameworks just for a new future Swift version!

**Comment by VTCoco** [comment]
However it means that Swift 4.2 can't be understood by a framework which embed Swift 5.0 and vice versa.

**Comment by VTCoco** [comment]
Closed due to inactivity, Swift 5 is coming with a stable ABI https://swift.org/blog/abi-stability-and-more/ 
It should patch this issue.
