### ISSUE TITLE
Installation is not possible.

### ISSUE THREAD

**Issue by Applr-techport** [voxeet/voxeet-uxkit-cordova#9]
I try to install and run it, but I can not run it.
this iOS version
xCode v10.2

sh-3.2# cordova plugin add cordova-plugin-voxeet
Installing "cordova-plugin-voxeet" for ios
Running command: /Users/Mac/Desktop/02.SI/13.Oritranslate/01.Hybrid/oritranslate.ios.1_0_12/plugins/cordova-plugin-voxeet/build_ios_frameworks.sh /Users/Mac/Desktop/02.SI/13.Oritranslate/01.Hybrid/oritranslate.ios.1_0_12
Installing "cordova-plugin-voxeet" ios dependencies (carthage)
*** Fetching voxeet-ios-conferencekit
*** Fetching voxeet-ios-sdk
*** Fetching Kingfisher
*** Checking out voxeet-ios-conferencekit at "1.1.6"
*** Checking out voxeet-ios-sdk at "1.3.4"
*** Checking out Kingfisher at "b5abf719d7e7428895542ebd5f0faa115b41a262"
*** xcodebuild output can be found in /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/carthage-xcodebuild.MdORgQ.log
*** Downloading voxeet-ios-sdk.framework binary at "1.3.4"
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace
Could not find any available simulators for iOS
Failed to install 'cordova-plugin-voxeet': Error: Hook failed with error code 1: /Users/Mac/Desktop/02.SI/13.Oritranslate/01.Hybrid/oritranslate.ios.1_0_12/plugins/cordova-plugin-voxeet/build_ios_frameworks.sh
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:239:23
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Hook failed with error code 1: /Users/Mac/Desktop/02.SI/13.Oritranslate/01.Hybrid/oritranslate.ios.1_0_12/plugins/cordova-plugin-voxeet/build_ios_frameworks.sh

help me please

**Comment by VTCoco** [comment]
Hello, I think you just need to upgrade your carthage with **brew upgrade carthage** :)

**Comment by Applr-techport** [comment]
Thank you for your reply.
I updated the carthage as you answered, but the same issue is happening.
Is there any other suspicious situation?

**Comment by VTCoco** [comment]
What is your current Carthage version? I think your problem is carthage related.
"Could not find any available simulators for iOS" comes from a carthage error. Make sure to update your Xcode (10.2 and launch it one time to install new command line tools), carthage (0.33.0).

**Comment by Applr-techport** [comment]
ok this problem carthage version
thank you
